export const ActionTypes = {
  FETCH_MAKES: "FETCH_MAKES",
  FETCH_MODELS: "FETCH_MODELS",
  FETCH_VERSIONS: "FETCH_VERSIONS",
  FETCH_VEHICLES: "FETCH_VEHICLES",
  CLEAR_ALL: "CLEAR_ALL",
  CLEAR_VERSIONS: "CLEAR_VERSIONS",
};
